lyon_is_wild_place:
    resource: "@LyonIsWildBundle/Resources/config/routing/place.yml"
    prefix:   /place

lyon_front:
    resource: "@LyonIsWildBundle/Resources/config/routing/default.yml"
    prefix:   /

